### ISSUE TITLE
カートに関する不具合のお知らせ

### ISSUE THREAD

**Issue by RouxRhett** [dwc-pomsky/NaganoCake#24]
現在developブランチに統合されているカート機能において以下の問題が発生しております。
・複数商品をカートに入れた際、カートの最後に追加された商品のみの合計が表示される
・カート内商品の単価価格に,がつかない
原因は特定できているので注文機能の実装時に修正を入れます。

**Comment by kazuki-77** [comment]
宜しくお願いします！

**Comment by RouxRhett** [comment]
解決できたので閉じます！
