### ISSUE TITLE
トップページから遷移するリンクについて

### ISSUE THREAD

**Issue by arakirina** [dwc-pomsky/NaganoCake#39]
トップページから、新着商品の詳細画面へ直接遷移できるリンクを貼り忘れているため、普通の商品名のみの記述のままになっている。

**Comment by arakirina** [comment]
### 商品詳細画面へ遷移するリンクを記述
- <%= link_to item.name, item_path(item.id), class: "item_#{item.id}" %>を記述し、商品名をクリックすることで、商品詳細へ直接遷移できるようにした。

**Comment by kazuki-77** [comment]
トップ画面に表示されている新着商品のリンクの場所が画像とのことなので変更をお願いします！

**Comment by arakirina** [comment]
確認します😃

**Comment by arakirina** [comment]
<p>
   <%= link_to item_path(item.id) do %>
     <%= attachment_image_tag item, :image, :fill, 250, 125, format:'jpeg'%>
   <% end %>
</p>

とすることで、商品画像にもリンクを適用させることができました🙌🏻
