### ISSUE TITLE
カート画面での遷移先について

### ISSUE THREAD

**Issue by arakirina** [dwc-pomsky/NaganoCake#40]
カート画面に設置されている「買い物を続ける」ボタンについて
テスト仕様書に、トップページへ遷移するように書かれていましたが
現状では、商品一覧が遷移先になっていました。

**Comment by RouxRhett** [comment]
パスを仕様書通りにしました。別ブランチにて修正中です。

**Comment by RouxRhett** [comment]
修正終わったので閉じます。
