### ISSUE TITLE
管理者側　注文一覧ページ（トップページ）の注文個数

### ISSUE THREAD

**Issue by kazuki-77** [dwc-pomsky/NaganoCake#42]
・注文個数がどんどん加算されていく状態

注文履歴が増えていくごとに過去の注文履歴の中の個数も増えていっている

<img width="1218" alt="スクリーンショット 2022-01-24 22 11 11" src="https://user-images.githubusercontent.com/93814427/150791085-e3b7dfda-cef7-4263-8fda-86eeb0a2554d.png">

**Comment by RouxRhett** [comment]
数値の計算時に初期化の作業がないからかもしれません

**Comment by kazuki-77** [comment]
sumメソッドを使ってカラムの合計を出すことによって繰り返しがたされることがなくなりました！
以下　参考記事です
https://qiita.com/tomokichi_ruby/items/8758a91566957cfc5429
