### ISSUE TITLE
会員一覧画面（管理者側）ステータスについて

### ISSUE THREAD

**Issue by kazuki-77** [dwc-pomsky/NaganoCake#45]
ワイヤーフレームでは会員ステータスが
有効（緑色）　退会済み（薄い灰色）になっているのが
falseとtrueで表示されているみたいです！

**Comment by arakirina** [comment]
確認します！

**Comment by arakirina** [comment]
教えてくださったif文で修正できました！🙌🏻🙇🏻‍♀️
